[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True

[mypy-pybaseball.*]
ignore_missing_imports = True

[mypy-functions_framework.*]
ignore_missing_imports = True
